package utils;
import webdsl.generated.templates.*;import java.util.ArrayList;
import java.util.List;
public class Statistics{
public static void logStatistics(){
List<PageStats> results=new ArrayList<PageStats>();
results.add(new PageStats().setPage("submitComplaint").setReadOnly(SubmitComplaintPage.renderReadOnly.getAndSet(0)).setReadOnlyFromCache(SubmitComplaintPage.renderReadOnlyFromCache.getAndSet(0)).setWithUpdates(SubmitComplaintPage.renderWithUpdates.getAndSet(0)).setActionFailed(SubmitComplaintPage.actionFailed.getAndSet(0)).setActionSuccessReadOnly(SubmitComplaintPage.actionSuccessReadOnly.getAndSet(0)).setActionSuccessWithUpdates(SubmitComplaintPage.actionSuccessWithUpdates.getAndSet(0)));
results.add(new PageStats().setPage("root").setReadOnly(RootPage.renderReadOnly.getAndSet(0)).setReadOnlyFromCache(RootPage.renderReadOnlyFromCache.getAndSet(0)).setWithUpdates(RootPage.renderWithUpdates.getAndSet(0)).setActionFailed(RootPage.actionFailed.getAndSet(0)).setActionSuccessReadOnly(RootPage.actionSuccessReadOnly.getAndSet(0)).setActionSuccessWithUpdates(RootPage.actionSuccessWithUpdates.getAndSet(0)));
results.add(new PageStats().setPage("pagenotfound").setReadOnly(PagenotfoundPage.renderReadOnly.getAndSet(0)).setReadOnlyFromCache(PagenotfoundPage.renderReadOnlyFromCache.getAndSet(0)).setWithUpdates(PagenotfoundPage.renderWithUpdates.getAndSet(0)).setActionFailed(PagenotfoundPage.actionFailed.getAndSet(0)).setActionSuccessReadOnly(PagenotfoundPage.actionSuccessReadOnly.getAndSet(0)).setActionSuccessWithUpdates(PagenotfoundPage.actionSuccessWithUpdates.getAndSet(0)));
results.add(new PageStats().setPage("findCustomer").setReadOnly(FindCustomerPage.renderReadOnly.getAndSet(0)).setReadOnlyFromCache(FindCustomerPage.renderReadOnlyFromCache.getAndSet(0)).setWithUpdates(FindCustomerPage.renderWithUpdates.getAndSet(0)).setActionFailed(FindCustomerPage.actionFailed.getAndSet(0)).setActionSuccessReadOnly(FindCustomerPage.actionSuccessReadOnly.getAndSet(0)).setActionSuccessWithUpdates(FindCustomerPage.actionSuccessWithUpdates.getAndSet(0)));
results.add(new PageStats().setPage("confirmation").setReadOnly(ConfirmationPage.renderReadOnly.getAndSet(0)).setReadOnlyFromCache(ConfirmationPage.renderReadOnlyFromCache.getAndSet(0)).setWithUpdates(ConfirmationPage.renderWithUpdates.getAndSet(0)).setActionFailed(ConfirmationPage.actionFailed.getAndSet(0)).setActionSuccessReadOnly(ConfirmationPage.actionSuccessReadOnly.getAndSet(0)).setActionSuccessWithUpdates(ConfirmationPage.actionSuccessWithUpdates.getAndSet(0)));
results.add(new PageStats().setPage("accessDenied").setReadOnly(AccessDeniedPage.renderReadOnly.getAndSet(0)).setReadOnlyFromCache(AccessDeniedPage.renderReadOnlyFromCache.getAndSet(0)).setWithUpdates(AccessDeniedPage.renderWithUpdates.getAndSet(0)).setActionFailed(AccessDeniedPage.actionFailed.getAndSet(0)).setActionSuccessReadOnly(AccessDeniedPage.actionSuccessReadOnly.getAndSet(0)).setActionSuccessWithUpdates(AccessDeniedPage.actionSuccessWithUpdates.getAndSet(0)));
results.add(new PageStats().setPage("noMessages").setReadOnly(NoMessagesPage.renderReadOnly.getAndSet(0)).setReadOnlyFromCache(NoMessagesPage.renderReadOnlyFromCache.getAndSet(0)).setWithUpdates(NoMessagesPage.renderWithUpdates.getAndSet(0)).setActionFailed(NoMessagesPage.actionFailed.getAndSet(0)).setActionSuccessReadOnly(NoMessagesPage.actionSuccessReadOnly.getAndSet(0)).setActionSuccessWithUpdates(NoMessagesPage.actionSuccessWithUpdates.getAndSet(0)));
results.add(new PageStats().setPage("showMessagesList_String_").setReadOnly(ShowMessagesList_String_Page.renderReadOnly.getAndSet(0)).setReadOnlyFromCache(ShowMessagesList_String_Page.renderReadOnlyFromCache.getAndSet(0)).setWithUpdates(ShowMessagesList_String_Page.renderWithUpdates.getAndSet(0)).setActionFailed(ShowMessagesList_String_Page.actionFailed.getAndSet(0)).setActionSuccessReadOnly(ShowMessagesList_String_Page.actionSuccessReadOnly.getAndSet(0)).setActionSuccessWithUpdates(ShowMessagesList_String_Page.actionSuccessWithUpdates.getAndSet(0)));
utils.PageStats.printList(results);
}
}
